mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.sodse.pojo
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springtest?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://localhost:3306/sodse?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      max-active: 50
      initial-size: 5
      default-transaction-isolation: 2
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: localhost
    timeout: 1000
  mvc:
    static-path-pattern: /static/**
  application:
    name: Client
  boot:
    admin:
      client:
        url: http://localhost:9999
qiniu:
  accessKey: PlGrVg42ThXjuPtdELkswJgiDPbZ_lVxantaE5cW
  secretKey: GX1pmhNXWvivsIA2Ke4iGxnLCVO3-4_Ujh2Lw3na
  bucket: imgof
  prefix: www-sodse-com-idvad2i.qiniudns.com
#
server:
  port: 8888

#server:
#  port: 80
